// <auto-generated />
namespace HOPApiService.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class InitialCreate : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207291337367_InitialCreate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAM1YzW7bRhC+F+g7EDy1h2gVFwgSg05gy1ZrNLKM0Ml9RY6kRZe7DHepSs+WQx+pr5BZ/i5JWSIlI+2NHM58MzscfjPDf7/9433YRtzZQKKYFFfu69HYdUAEMmRideWmevnqrfvh/c8/eXdhtHW+lHoXRg8thbpy11rHl4SoYA0RVaOIBYlUcqlHgYwIDSW5GI/fktdjAgjhIpbjeJ9SoVkE2Q3eTqQIINYp5TMZAleFHJ/4GarzQCNQMQ3gyv1j/ngdMx+SDQtglOu7zjVnFGPxgS8HBjZ+ZwJzK5fo9A6D07unXQyZ48ynrYAqf8KuIUDRYyJjSPTuEywLs/vQdUjTjrQNKzPLxnjGK6F/u3Cdh5RzuuAoWFKuwHXiN5e+lgn8DgISqiF8pFpDIowtZJEXGbiM3/RLwjsyvjBJIFQIqanGV9wJvBXmdRgmoFQZq68TLBjXmbIthB9BrPS6indGt6UEL13ns2BYX2ikkxTs8+X3h/3eRZTx/8q5/3Wqj72dwwg3EKozEahenwkx/xsL54cn7xZLFV8cVPVtBE9IAoPjv4/oCm52Gqo83DBBk12/QwyLOvM1ZRzM7Q/P2WOCHFflS6ZoODhbH/F71ml4NowUq+E4Hqm5tMuwSPuaMizGukSokcFWt+g21/dBl4QsY3z5NXbO/CPD03v9V57qzkLy1lK2IPJMD/JmNI7xbVs9qZA4ft6QJq/84S0nyjFIoPZ0nirayhPyPdZh6ym6xkinLFHaZG5BTfYnYdRR65HX0pOV3nZ/q7NdKpvrqkF2mvKo0zXt7E3xQBG2q+xsUMWxp9cWdn5AOU32dMuJ5Gkknuu4h6yrPmJDVML+OM2mZIM1n/RHzDuNjZRL+iPkncZGyCUDEPJO04DIRf0xilZjYxSi/hhW47BxLHF/LLt1NOrGkg9Eq5tDB7B+1B+zoHwbqxD1x6gp34appQOQatZvQNXiLpZHWp94m0hIh0laM3Kb"
                       + "lQ4Relul8l4Re4vAvYJMj28aHXbNVVwHk7RhoWFWf6c0RCOjMPK/8glneN5aYUYFW4LST/IvMFsTkv/pq0o1pSsV8v/hvsLMyY9uJgPHjtaoLzY0CdY0+SWi219fYnc4C9DeB7LTn7ENnGRv7wKnADQ2gbNS0ZnuQxTol5nuMa5FNuCfFNneCf6sszam8iWXdHji20P5iSjtmbwPzLCRvDthHhnMzQS+fy7P2RMrYyEx3jw+fKBOnti7RO4R+8eSdwuKrWoI85tJQGB+b9Sgpc69WMoyvXgcO6JSpZX9GWiKVU6vE82WNND4OEBmyTbDL5SnGeMsILwX81THqb5WCqIF39nn9chh/9la0ozZm8fmTr3EETBMZj7UubhJGQ+ruKd7yuYZCFMgBd9jVLgZI9xqVyE9SNETqEjfLcQgTLd4gijmCKbmwqcbeD624zlsZsy7ZXSV0EgVGLW9+c9JzI/O998B7N8RfBoVAAA="; }
        }
    }
}
